### PR TITLE
Updates cmake to 0.1.40 in harfbuzz-sys 0.3.0

### PR DESCRIPTION
**Pull request by nhristov**
This fixes https://github.com/maps4print/azul/issues/163

### CODE REVIEW

**Comment by fschutt** [comment]
Well, I'll merge it, but it's only a temporary fix - currently I'm unvendoring all the crates and upstreaming the things I've changed. But thanks, for now it's probably better to do it this way.

**Comment by Prid13** [comment]
This is still not working for me :/ Running `cargo run` doesn't install the latest version of cmake, but rather `v.0.1.35`, which is causing the same error as the [original thread](https://github.com/maps4print/azul/issues/163).

Help would be really appreciated, as I've spent a few hours pulling my hair trying to get this work as it's my first encounter with azul and I'm really interested in trying it out.

**Comment by nhristov** [comment]
@Prid13 That's because the **azul-dependencies** in azul/cargo/azul/Cargo.toml from the https://github.com/maps4print/azul repository is still pointing to the previous revision - _bf2933b9aac43a7003278862772250398e4fa457_

To fix this, remove the **rev** or point to this one instead - _b61fe8d931ea5f46fdce05944f5fde8ca4cd6931_

**Comment by Prid13** [comment]
Thanks for the quick reply! I'm pulling the git repo of azul as a dependency in my sample app, so I have no direct access to the source code. Here are the dependencies part of my `Cargo.toml` file:

    [dependencies]
    azul = { git = "https://github.com/maps4print/azul" }

How am I supposed to change the revision without downloading the files and editing manually? I tried patching, but it didn't work:

    [patch.'https://github.com/maps4print/azul-dependencies']
    azul-dependencies = { git = "https://github.com/maps4print/azul-dependencies", rev = "b61fe8d" }

It's just giving me an error on build about the patch pointing to the same source. Any help would be appreciated :)

**Comment by nhristov** [comment]
I have opened these two https://github.com/maps4print/azul/pull/194 https://github.com/maps4print/azul/pull/195 for you, but for now you can download, change and import the https://github.com/maps4print/azul repository manually.

**Comment by Prid13** [comment]
Many thanks for the help! I'm completely new to rust and cargo, so I'm going to have to ask for some more help :) How do I use it after downloading the repo? I tried adding this to my Cargo.toml:

    [dependencies]
    azul = { path = "azul-master" }

But it didn't work:

`error: failed to load source for a dependency on `azul``

Then I tried running `cargo build` inside the imported repo folder, but I forgot to change the version of cmake. I tried changing it and running the `build` command again, but I'm getting this error now:

image

Hope you can resolve this :)

**Comment by nhristov** [comment]
@Prid13 You're almost there. The cargo files for azul are located inside **azul/cargo/azul**. Assuming you named the downloaded repository **azul-master**, insert the following in your Cargo.toml file

```toml
[dependencies]
azul = { path = "azul-master/cargo/azul" }
```

**Comment by Prid13** [comment]
Hooray, it worked! 😃 Thank you so much for your help 💯 

However, going through the Getting Started tutorial, compiling and running the Simple Counter app gives me a blank window, and running the Calculator example gave me an app with a broken UI -- like [this issue](https://github.com/maps4print/azul/issues/174).

I really appreciate your patience and help, but I don't think this framework is working for me, and I think I'm going to go with Sciter since their examples are working on my computer. Hope this works out in the future :)

**Pull request merged**
